<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\..\src\crucible\scripting\dotnet\Crucible-Runtime\Crucible-Runtime\Crucible-Runtime.csproj" />
    </ItemGroup>

</Project>
